---

name: Cargo Build & Test

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install toolchain
        run: |
          rustup update ${{ matrix.toolchain }} && \
          rustup default ${{ matrix.toolchain }}

      - name: Install libnotify
        run: |
          sudo apt-get update
          sudo apt-get install libnotify-dev

      - name: Use cache
        uses: Swatinem/rust-cache@v2

      - name: Build with ${{ matrix.toolchain }}
        run: cargo build --verbose

      # there are no tests
      #- name: Check with ${{ matrix.toolchain }}
      #  run: cargo check --verbose
