---

name: build release artifacts

permissions:
  contents: write

on:  # yamllint disable-line rule:truthy
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create packed release binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: scun
          tar: unix
          token: ${{ secrets.GITHUB_TOKEN }}
